version: '3.8'
services:
  notifier:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=projectnotifpass